[settings]
csv_delimiter = "\t"
null_values = ["\\n", "", "na", "unk", "null", "none", "nan", "1/0/00", "1/0/1900"]
boolean_true = ["true", "t", "yes", "y", "1"]
boolean_false = ["false", "f", "no", "n", "0"]
dollar_to_cent = true
percent_to_decimal = true
add_digits_to_decimal_field = 2
add_to_string_length = 32
datetime_allowed_characters = "0123456789/:-t."
datetime_formats = ["%m/%d/%y", "%m/%d/%Y", "%Y%m%d", "%Y-%m-%d"]
field_name_full_conversion = [["carrot", "cheese"], ["BREAD", "salted butter"], ["Model Year", "Year"]]
field_name_part_conversion = [["#", "num"], [" (e)", ""], ["(y/n)", ""], [" (s)", ""], [" (e,s)", ""], ["yyyymmdd", ""], [")", ""], ["(", ""], [": ", "_"], [" ", "_"], ["/", "_"], [".", "_"], ["-", "_"], ["%", "_percent"], ["?", ""], ["!", ""], [",", ""], ["'", ""], ["&", "_and_"], ["@", "_at_"], ["$", "_dollar_"], [">=", "_bigger_or_equal_"], [">", "_bigger_"], ["<=", "_less_or_equal_"], ["<", "_less_"], ["=", "_equal_"], ["___", "_"], ["__", "_"]]
should_reprocess = false  # Whether to reprocess files that are already processed or not. The recommended value is false so we avoid reprocessing files that are already processed before.
dollar_value_if_word_in_field_name = []
non_string_fields_are_all_nullable = true
string_fields_can_be_nullable = false
training_csvs = ['../../tests/fixtures/training_fixture1.tsv']
output_model_file = 'tsv_sample_model.py'
ignore_lines_that_include_only_subset_of = ["", "-"]
ignore_fields_in_signature_calculation = ["id", "raw_key_id"]
ignore_duplicate_rows_when_importing = true
encrypt_raw_data_during_backup = true
fields_to_be_encrypted = []
slack_username = ""
slack_channel = ""
slack_http_endpoint = ""
slack_handle_to_ping = ""
identify_header_by_column_names = []

[settings.max_int]
"SmallInteger" = 32767
"Integer" = 2147483647
"BigInteger" = 9223372036854775807
