apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx 
          image: nginx:latest 
          resources:
            requests:
              cpu: 20m
              memory: 100Mi
          ports:
            - containerPort: 80 
